### ISSUE TITLE
Make nightly features appear in docs.rs

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#123]
This would involve adding:

```toml
[package.metadata.docs.rs]
features = ["nightly"]
```
to `Cargo.toml`
