### ISSUE TITLE
Use OpenBLAS/BLAS/IntelMKL for matrix multiplication

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#18]
Currently using the matrixmultiply crate, but I think performance could be much improved with using the actual BLAS library. Unclear how compiling/including that works since it has to be compiled per machine.

**Comment by coreylowman** [comment]
```toml
[dependencies]
blas = "0.22.0"
blas-src = { version = "0.8", features = ["openblas"] }
openblas-src = { version = "0.10", features = ["cblas", "system"] }
```

**Comment by coreylowman** [comment]
First attempt... the arguments aren't correct though.

```rust
extern crate blas_src;

fn matmul<const M: usize, const N: usize, const K: usize>(
    a: &[[f32; K]; M],
    b: &[[f32; N]; K],
) -> [[f32; N]; M] {
    let mut c = [[0.0; N]; M];
    unsafe {
        let a = std::slice::from_raw_parts(a.as_ptr() as *const f32, 0);
        let b = std::slice::from_raw_parts(b.as_ptr() as *const f32, 0);
        let c = std::slice::from_raw_parts_mut(c.as_mut_ptr() as *mut f32, 0);
        blas::sgemm(
            b'T', b'T', M as i32, N as i32, K as i32, 1.0, a, K as i32, b, N as i32, 0.0, c,
            M as i32,
        )
    }
    c
}
```

**Comment by coreylowman** [comment]
Here's a cblas_sys function to call

```toml
[dependencies]
cblas-sys = "0.1.4"
libc = "0.2.126"
```

```rust
pub fn mkl_mm<const M: usize, const N: usize, const K: usize>(
    a: &[[f32; K]; M],
    b: &[[f32; N]; K],
    c: &mut [[f32; N]; M],
) {
    unsafe {
        cblas_sys::cblas_sgemm(
            cblas_sys::CblasRowMajor,
            cblas_sys::CblasNoTrans,
            cblas_sys::CblasNoTrans,
            M as libc::c_int,
            N as libc::c_int,
            K as libc::c_int,
            1.0 as libc::c_float,
            a.as_ptr() as *const libc::c_float,
            K as libc::c_int,
            b.as_ptr() as *const libc::c_float,
            N as libc::c_int,
            0.0 as libc::c_float,
            c.as_mut_ptr() as *mut libc::c_float,
            N as libc::c_int,
        )
    }
}
```
