### ISSUE TITLE
Combine "intel-mkl" and "cblas" feature flag & remove "cblas"

### ISSUE THREAD

**Issue by coreylowman** [coreylowman/dfdx#546]
Currently the features look like:
```toml
cblas = ["dep:cblas-sys", "dep:libc"]
intel-mkl = ["cblas"]
```
Where cblas is just an internal feature not intended to be used by the end user.

Would like to remove the cblas feature all together (and just have "intel-mkl").

This involves
1. Fixing the Cargo.toml
2. Replacing any usages of `feature = "cblas"` in src with `feature = "intel-mkl"`
